OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "sk-tH6ClBmIJHhFrFCOA26c08Fa142644A0A3Fb79849eCd162b"

GLMModel:
  model_url: "https://api.xiaoai.plus/v1"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"